#! /usr/bin/perl -w

# Tool to obtain source files needed to build SRPM.
# Copyright (C) 2016 Red Hat, Inc.
# Written by Pavel Raiskup <praiskup@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

use Cwd;
use File::Basename;

sub info
{
    print (" * @_\n");
}

my ($specfile, $output) = @ARGV;

if (not defined $specfile) {
  die "Need specfile\n";
}
if (not defined $output) {
  $output=".";
  info "use default output dir .";
}


my @sources = `spectool $specfile -S`;
if ($? >> 8) {
    die ("can't successfully run 'spectool'");
}

# Go through all 'SourceN' statements in spec file.
for my $source_line (@sources)
{
    chomp $source_line;
    my ($id, $source) = split (/ /, $source_line, 2);
    $id =~ s/:$//;
    $id = lc ($id);

    my $src_basename = basename ($source);
    if (-f "$output/$src_basename") {
        info "$src_basename already exists";
        next;
    }


    info ("downloading sources $source");
    system ("wget", "-P", "$output", "-q", "$source");
    if ($? >> 8) {
        die ("can't wget $source");
    }
}
